"""baseline: esquema inicial desde los modelos

Revision ID: 7b8bb7dc02fa
Revises: 
Create Date: 2026-09-01 16:48:36.094893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '7b8bb7dc02fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TEXT_GENERATION', 'TEXT_EMBEDDING', 'SPEECH_TO_TEXT', 'TEXT_TO_SPEECH', 'IMAGE_GENERATION', 'IMAGE_EDIT', 'VIDEO_GENERATION', 'VIDEO_ASSEMBLY', 'MULTIMODAL_PIPELINE', 'AUTONOMOUS_MISSION', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'NORMAL', 'LOW', 'ARQ_PREFIX', name='jobpriority'), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_detail', sa.JSON(), nullable=True),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_job_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_step_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_priority'), 'jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_jobs_provider'), 'jobs', ['provider'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('llm_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('requested_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_equivalent_usd', sa.Float(), nullable=True),
    sa.Column('priced', sa.Boolean(), nullable=False),
    sa.Column('cache', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('searched', sa.Boolean(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_requests_cache'), 'llm_requests', ['cache'], unique=False)
    op.create_index(op.f('ix_llm_requests_client_id'), 'llm_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_llm_requests_created_at'), 'llm_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_requests_error_kind'), 'llm_requests', ['error_kind'], unique=False)
    op.create_index(op.f('ix_llm_requests_family'), 'llm_requests', ['family'], unique=False)
    op.create_index(op.f('ix_llm_requests_job_id'), 'llm_requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_llm_requests_outcome'), 'llm_requests', ['outcome'], unique=False)
    op.create_index(op.f('ix_llm_requests_project'), 'llm_requests', ['project'], unique=False)
    op.create_index(op.f('ix_llm_requests_requested_model'), 'llm_requests', ['requested_model'], unique=False)
    op.create_index(op.f('ix_llm_requests_response_model'), 'llm_requests', ['response_model'], unique=False)
    op.create_index(op.f('ix_llm_requests_route'), 'llm_requests', ['route'], unique=False)
    op.create_index(op.f('ix_llm_requests_trace_id'), 'llm_requests', ['trace_id'], unique=False)
    op.create_table('registered_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('resource_requirements', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_models_is_available'), 'registered_models', ['is_available'], unique=False)
    op.create_index(op.f('ix_registered_models_model_id'), 'registered_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_registered_models_provider'), 'registered_models', ['provider'], unique=False)
    op.create_table('worker_runtimes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_job_id', sa.Uuid(), nullable=True),
    sa.Column('jobs_processed', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_event_type'), 'job_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_events_occurred_at'), 'job_events', ['occurred_at'], unique=False)
    op.create_table('llm_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['llm_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_attempts_created_at'), 'llm_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_attempts_model'), 'llm_attempts', ['model'], unique=False)
    op.create_index(op.f('ix_llm_attempts_outcome'), 'llm_attempts', ['outcome'], unique=False)
    op.create_index(op.f('ix_llm_attempts_request_id'), 'llm_attempts', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_attempts_request_id'), table_name='llm_attempts')
    op.drop_index(op.f('ix_llm_attempts_outcome'), table_name='llm_attempts')
    op.drop_index(op.f('ix_llm_attempts_model'), table_name='llm_attempts')
    op.drop_index(op.f('ix_llm_attempts_created_at'), table_name='llm_attempts')
    op.drop_table('llm_attempts')
    op.drop_index(op.f('ix_job_events_occurred_at'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_event_type'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('worker_runtimes')
    op.drop_index(op.f('ix_registered_models_provider'), table_name='registered_models')
    op.drop_index(op.f('ix_registered_models_model_id'), table_name='registered_models')
    op.drop_index(op.f('ix_registered_models_is_available'), table_name='registered_models')
    op.drop_table('registered_models')
    op.drop_index(op.f('ix_llm_requests_trace_id'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_route'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_response_model'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_requested_model'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_project'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_outcome'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_job_id'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_family'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_error_kind'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_created_at'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_client_id'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_cache'), table_name='llm_requests')
    op.drop_table('llm_requests')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_provider'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_priority'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_client_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
